<a href="https://colab.research.google.com/github/danielroa98/Redes-Neuronales/blob/main/A01021960_Perceptron_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Perceptron Algorithm

A Perceptron is a system that learns using labeled examples of feature vectors, mapping these inputs to their corresponding output class labels. In its simplest form, a Perceptron contains N input nodes, one for each entry in the input row, followed by only one layer in the network with just a single node in that layer.

Training a Perceptron is a fairly straightforward operation. Our goal is to obtain a set of weights *w* that accurately classifies each instance in our training set. In order to train our Perceptron, we iteratively feed the network our training data multiple times. Each time the network has seen the full set of training data, we say an epoch has passed. It normally takes many epochs until a weight vector _w_ can be learned to linearly separate our two classes of data.

![Perceptron](https://drive.google.com/uc?id=1K7olbB11mSfAwPmB8BeeRNe6XbuGSK4D)

The pseudocode is the following:
1. Initialize our weight vector w with small random values
2. Until Perceptron converges
    1. Loop over each input and class label
    2. Take $x$ and pass it through the network, calculating the output value: $y = (w · x)$
    3. Update the weights: if ŷ = 0 --> $w_i = w_i + \alpha x_i$, if ŷ = 1 --> $w_i = w_i - \alpha x_i$
        

# Script using Numpy
## Daniel Roa - A01021960
## Delivery date: 12/07/2021

In [ ]:
import random, math
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
class Perceptron:        
    """Perceptron class

        Args:
            M: Number of inputs
            alpha: Learning rate
        
        Attributes:
            W: The weights for the perceptron
            b: bias
            alpha: The learning rate
    """
    def __init__(self, N, M, alpha=0.5):        
        # Creates an array of N weights and initializes with random values
        # define inputs
        self.alpha = alpha
        self.b = np.random.rand(1, 1)
        self.error = []
        self.M = M
        self.posX = []
        self.W = np.random.uniform(0, 1, size=N)
            
    def sigmoid(self, x):
        return (1/(1 + math.e**(-x)))

    def loss(self, yHat, y):
      '''
        Function in charge of calculating the Loss function (L).

        Args:
          yHat: equals to y with a hat on a regular equation, it's the predictions' values.
          y: 
      '''
      return (-(y * np.log(yHat) + (1 - y) * np.log(1 - yHat)))

    
    def predict(self, x):
        """
            Makes a prediction for the specified input
            
            Args:
                x: Input to make a prediction on.
        """
        return self.sigmoid(np.dot(x, self.W)+ self.b)
    
    def perceptronStep(self, X, y):
        """
            The perceptron basic step. It updates the weights based on the input data.
            
            Args:
                X: Array with the input data
                y: Data labels
        """
        # Variables that will hold different information
        J = 0
        L = 0
        db = 0
        dw = 0
        dw1 = 0
        dw2 = 0
        
        # yHat = self.sigmoid(np.dot(X, self.W) + self.b)
        yHat = self.predict(X)
        J += self.loss(yHat, y)

        dy = yHat - y
        dw += np.dot(X.T, dy) / self.M
        db += dy / self.M

        # IMPORTANT
        # Couldn't fix the self.b -= (db * self.alpha) issue
        # Couldn't fix the self.W -= (dw * self.alpha) issue
        self.W = (dw * self.alpha)
        self.b = (db * self.alpha)

        return
    
    def train(self, X, y, epochs = 10):
        """
            Runs the perceptron step a specified number of epochs
            
            Args:
                X: input data
                y: labels
                epochs: The number of times the step is executed
        """
        # loop over the desired epochs
        for epoch in range(epochs):
            self.perceptronStep(X, y)
        return


## Execution of the AND data

In [ ]:
# change the seed to see different solutions
random.seed(42)

# The following data is used to train the perceptron for the AND operation
# Test your code with the OR operation
X = np.array([[0,0],[0,1], [1,0], [1,1]])
y = np.array([[0],[0], [0], [1]])

m = len(y)

p = Perceptron(2, m)
print(f"Initial weights {p.W}")
# print(f'Shapes\nInput X {X.shape}\nInput y {y.shape}\nWeights {p.W.shape}')

# Test training with different epochs
p.train(X, y, 25)
print(f"Weights after training {p.W}")

# Test your model with a prediction
prediction = p.predict(np.array([0,1]))
print(f'Prediction for {[0, 1]} is {p.predict(np.array([0,1]))}')
# print(f'Prediction for {X[1]} is {p.predict(X[1])}')
# print(f'Prediction for {X[2]} is {p.predict(X[2])}')
# print(f'Prediction for {X[3]} is {p.predict(X[3])}')


Initial weights [0.3944054  0.99227021]
Weights after training [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Prediction for [0, 1] is [[0.51612326 0.51612326 0.51612326 0.51612326]
 [0.51612326 0.51612326 0.51612326 0.51612326]
 [0.51612326 0.51612326 0.51612326 0.51612326]
 [0.48387674 0.48387674 0.48387674 0.48387674]]


## Execution of the OR data

In [ ]:
# change the seed to see different solutions
random.seed(42)

# The following data is used to train the perceptron for the AND operation
# Test your code with the OR operation
X = np.array([[0,0],[0,1], [1,0], [1,1]])
# OR data
y = np.array([[0],[1], [1], [1]])

m = len(y)

p = Perceptron(2, m)
print(f"Initial weights {p.W}")
# print(f'Shapes\nInput X {X.shape}\nInput y {y.shape}\nWeights {p.W.shape}')

# Test training with different epochs
p.train(X, y, 25)
print(f"Weights after training {p.W}")

# Test your model with a prediction
prediction = p.predict(np.array([0,1]))
print(f'Prediction for {[0, 1]} is {p.predict(np.array([0,1]))}')

#print(f'Prediction for {X[1]} is {p.predict(X[1])}')
#print(f'Prediction for {X[2]} is {p.predict(X[2])}')
#print(f'Prediction for {X[3]} is {p.predict(X[3])}')


Initial weights [0.54670772 0.51992338]
Weights after training [[-0.14269306 -0.14269306 -0.14269306 -0.14269306]
 [-0.14269306 -0.14269306 -0.14269306 -0.14269306]]
Prediction for [0, 1] is [[0.48046553 0.48046553 0.48046553 0.48046553]
 [0.44725033 0.44725033 0.44725033 0.44725033]
 [0.44725033 0.44725033 0.44725033 0.44725033]
 [0.44613672 0.44613672 0.44613672 0.44613672]]


# Fixes seen in class

In [ ]:
import random, math
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
class Perceptron:        
    """Perceptron class

        Args:
            M: Number of inputs
            alpha: Learning rate
        
        Attributes:
            W: The weights for the perceptron
            b: bias
            alpha: The learning rate
    """
    def __init__(self, N, M, alpha=0.5):        
        # Creates an array of N weights and initializes with random values
        # define inputs
        self.alpha = alpha
        # self.b = np.random.rand(1, 1)
        self.b = random.uniform(0, 1) # Corrected version
        self.error = []
        self.M = M
        self.posX = []
        # self.W = np.random.uniform(0, 1, size=N)
        self.W = np.random.rand(2, 1) # Corrected version 2 <- representa los inputs 1 <- representa los # de conexiones de la siguiente capa 

    def sigmoid(self, x):
        return 1 / 1(np.exp(-x)) # <- esta preparado para recibir valores específicos de Numpy
    
    def sigmoid_der(x):
      return (x)*(1-(x))

    def loss(self, yHat, y):
      '''
        Function in charge of calculating the Loss function (L).

        Args:
          yHat: equals to y with a hat on a regular equation, it's the predictions' values.
          y: 
      '''
      return (-(y * np.log(yHat) + (1 - y) * np.log(1 - yHat)))

    
    def predict(self, x):
        """
            Makes a prediction for the specified input
            
            Args:
                x: Input to make a prediction on.
        """
        return self.sigmoid(np.dot(x, self.W)+ self.b)
    
    def perceptronStep(self, X, y):
        """
            The perceptron basic step. It updates the weights based on the input data.
            
            Args:
                X: Array with the input data
                y: Data labels
        """
        # Variables that will hold different information
        J = 0
        L = 0
        db = 0
        dw = 0
        dw1 = 0
        dw2 = 0
        
        # yHat = self.sigmoid(np.dot(X, self.W) + self.b)
        yHat = self.predict(X)
        J += self.loss(yHat, y)

        dy = yHat - y
        dw += np.dot(X.T, dy) / self.M
        db += dy / self.M

        # IMPORTANT
        # Couldn't fix the self.b -= (db * self.alpha) issue
        # Couldn't fix the self.W -= (dw * self.alpha) issue
        self.W = (dw * self.alpha)
        self.b = (db * self.alpha)

        return
    
    def train(self, X, y, epochs = 10):
        """
            Runs the perceptron step a specified number of epochs
            
            Args:
                X: input data
                y: labels
                epochs: The number of times the step is executed
        """
        # loop over the desired epochs
        for epoch in range(epochs):
            self.perceptronStep(X, y)
        return


In [ ]:
# change the seed to see different solutions
random.seed(42)

# The following data is used to train the perceptron for the AND operation
# Test your code with the OR operation
X = np.array([[0,0],[0,1], [1,0], [1,1]]).T
y = np.array([[0],[0], [0], [1]])

m = len(y)

p = Perceptron(2, m)
print(f"Initial weights {p.W}")
# print(f'Shapes\nInput X {X.shape}\nInput y {y.shape}\nWeights {p.W.shape}')

# Test training with different epochs
p.train(X, y, 25)
print(f"Weights after training {p.W}")

# Test your model with a prediction
prediction = p.predict(np.array([0,1]))
print(f'Prediction for {[0, 1]} is {p.predict(np.array([0,1]))}')
# print(f'Prediction for {X[1]} is {p.predict(X[1])}')
# print(f'Prediction for {X[2]} is {p.predict(X[2])}')
# print(f'Prediction for {X[3]} is {p.predict(X[3])}')
